groups:
- name: instances
  interval: 10s 
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
      labelscount: "{{ len $labels }}"
    annotations:
      summary: "Экземпляр {{ $labels.instance }} недоступен"
      description: "Экземпляр {{ $labels.instance }} для работы {{ $labels.job }} не отвечает более 1 минуты."
