services:
  prometheus:
    image: prom/prometheus
    ports:
      - "192.168.0.39:9090:9090"
    volumes:
      - ./prometheus/configuration/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "192.168.0.39:3000:3000"
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    ports:
      - "192.168.0.39:9100:9100"
    restart: unless-stopped
