# blackbox-exporter/config.yml
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [] # Любой 2xx код считается успехом
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: false
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
